apiVersion: apps/v1
kind: Deployment
metadata:
  name: nef
  labels:
    app: nef
spec:
  selector:
    matchLabels:
      app: nef
  replicas: 1
  template:
    metadata:
      labels:
        app: nef
    spec:
      ServiceAccountName: nef-account
      containers:
        - name: nef
          image: jacintoluf/nef:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          #added
          # envFrom:
          #   secretKeyVaRef:
          #     name: db-secret
      imagePullSecrets:
        - name: dockerhub-secret

---
apiVersion: v1
kind: Service
metadata:
  name: nef
  labels:
    app: nef
spec:
  #added
  clusterIP: 10.102.141.12
  clusterIPs:
    - 10.102.141.12
  ports:
  - port: 80
    protocol: TCP
    name: nef
    targetPort: 80
  selector:
    app: nef
  #type: LoadBalancer
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nef-mongodb
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nef-mongodb
  claimRef:
    name: nef-mongodb
    namespace: open5gs
  hostPath:
    path: /mnt/nef/mongodb
    type: ''
  volumeMode: Filesystem

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nef-account
#automountServiceAccountToken: false

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: open5gs
  name: nef-services-read
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nef-services-read-rb
subjects:
- kind: ServiceAccount
  name: nef-account
  namespace: open5gs
roleRef:
  kind: Role
  name: nef-services-read
  apiGroup: ""