---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-nef-deployment
  labels:
    app: nef
spec:
  selector:
    matchLabels:
      app: nef
  replicas: 1
  template:
    metadata:
      labels:
        app: nef
    spec:
      containers:
        - name: dummy-nef-deployment
          image: jacintoluf/nef:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: dockerhub-secret

---
apiVersion: v1
kind: Service
metadata:
  name: dummy-nef-deployment
  labels:
    app: nef
spec:
  ports:
  - port: 80
    protocol: TCP
    name: nef
    targetPort: 80
  selector:
    app: nef
  type: LoadBalancer