---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nef-deployment
  labels:
    app: nef
spec:
  selector:
    matchLabels:
      app: nef
  replicas: 1
  template:
    metadata:
      labels:
        app: nef
    spec:
      containers:
        - name: nef
          image: jacintoluf/nef:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: dockerhub-secret

---
apiVersion: v1
kind: Service
metadata:
  name: nef
  labels:
    app: nef
spec:
  #added
  #clusterIP: 10.102.141.12
  #clusterIPs:
  #  - 10.102.141.12
  ports:
  - port: 80
    protocol: TCP
    name: nef
    targetPort: 80
  selector:
    app: nef
  type: LoadBalancer
  #type: clusterIP