apiVersion: apps/v1
kind: Deployment
metadata:
  name: nef
  labels:
    app: nef
spec:
  selector:
    matchLabels:
      app: nef
  replicas: 1
  template:
    metadata:
      labels:
        app: nef
    spec:
      serviceAccount: default
      serviceAccountName: default
      containers:
        - name: nef
          image: jacintoluf/nef:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          #added
          # envFrom:
          #   secretKeyVaRef:
          #     name: db-secret
      imagePullSecrets:
        - name: dockerhub-secret

---
apiVersion: v1
kind: Service
metadata:
  name: nef
  labels:
    app: nef
spec:
  #added
  clusterIP: 10.102.141.12
  clusterIPs:
    - 10.102.141.12
  ports:
  - port: 80
    protocol: TCP
    name: nef
    targetPort: 80
  selector:
    app: nef
  #type: LoadBalancer
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nef-mongodb
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nef-mongodb
  claimRef:
    name: nef-mongodb
    namespace: open5gs
  hostPath:
    path: /mnt/nef/mongodb
    type: ''
  volumeMode: Filesystem

# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: nef-account
# automountServiceAccountToken: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pods-list
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pods-list
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: pods-list
  apiGroup: rbac.authorization.k8s.io