apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${NAME}
  labels:
    app: ${NAME}
spec:
  selector:
    matchLabels:
      app: ${NAME}
  replicas: 1
  template:
    metadata:
      labels:
        app: ${NAME}
    spec:
      serviceAccountName: ${NAME}-account
      containers:
        - name: ${NAME}
          image: jacintoluf/nf-nef:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 7777
          env:
            - name: NAME
              value: ${NAME}
            - name: CORE_5G
              value: ${CORE_5G}
            - name: NAMESPACE
              value: ${NAMESPACE}
            - name: PLMN
              value: ${PLMN}
---
apiVersion: v1
kind: Service
metadata:
  name: ${NAME}
  labels:
    app: ${NAME}
spec:
  ports:
  - name: ${NAME}
    protocol: TCP
    port: 7777
    targetPort: 7777
    nodePort: 7777
  selector:
    app: ${NAME}
  type: NodePort

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${NAME}-account
  namespace: ${NAMESPACE}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pods-list-${NAME}
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pods-list-${NAME}
subjects:
- kind: ServiceAccount
  name: ${NAME}-account
  namespace: ${NAMESPACE}
roleRef:
  kind: ClusterRole
  name: pods-list-${NAME}
  apiGroup: rbac.authorization.k8s.io