apiVersion: apps/v1
kind: Deployment
metadata:
  name: nef
  labels:
    app: nef
spec:
  selector:
    matchLabels:
      app: nef
  replicas: 1
  template:
    metadata:
      labels:
        app: nef
    spec:
      serviceAccountName: nef-account
      containers:
        - name: nef
          image: jacintoluf/nf-nef:${CORE_5G}
          imagePullPolicy: Always
          ports:
            - containerPort: 7777
          env:
            - name: CORE_5G
              value: ${CORE_5G}
            - name: NAMESPACE
              value: ${NAMESPACE}
      imagePullSecrets:
        - name: dockerhub-secret

---
apiVersion: v1
kind: Service
metadata:
  name: nef
  labels:
    app: nef
spec:
  ports:
  - name: nef
    protocol: TCP
    port: 7777
    targetPort: 7777
    nodePort: 7777
  selector:
    app: nef
  type: NodePort
  #type: ClusterIP

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nef-account
  namespace: ${NAMESPACE}
#automountServiceAccountToken: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pods-list-nef
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pods-list-nef
  #namespace: ${NAMESPACE}
subjects:
- kind: ServiceAccount
  name: nef-account
roleRef:
  kind: ClusterRole
  name: pods-list-nef
  apiGroup: rbac.authorization.k8s.io