apiVersion: apps/v1
kind: Deployment
metadata:
  name: udp-echo-server
  labels:
    app: udp-echo-server
spec:
  selector:
    matchLabels:
      app: udp-echo-server
  replicas: 1
  template:
    metadata:
      labels:
        app: udp-echo-server
    spec:
      containers:
        - name: udp-echo-server
          image: jacintoluf/nef:udp
          imagePullPolicy: Always
          ports:
            - containerPort: 80
        - name: terminal
          image: ubuntu:latest
          imagePullPolicy: Always
          command: ["sleep", "infinity"]
      imagePullSecrets:
        - name: dockerhub-secret

---
apiVersion: v1
kind: Service
metadata:
  name: udp-echo-server
  labels:
    app: udp-echo-server
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: UDP
  selector:
    app: udp-echo-server
