apiVersion: apps/v1
kind: Deployment
metadata:
  name: udp-echo-server2
  labels:
    app: udp-echo-server2
spec:
  selector:
    matchLabels:
      app: udp-echo-server2
  replicas: 1
  template:
    metadata:
      labels:
        app: udp-echo-server2
    spec:
      containers:
        - name: udp-echo-server2
          image: jacintoluf/nef:udp
          imagePullPolicy: Always
          ports:
            - containerPort: 80
        # - name: terminal
        #   image: ubuntu:latest
        #   imagePullPolicy: Always
        #   command: ["sleep", "infinity"]
      imagePullSecrets:
        - name: dockerhub-secret

---
apiVersion: v1
kind: Service
metadata:
  name: udp-echo-server2
  labels:
    app: udp-echo-server2
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: UDP
  selector:
    app: udp-echo-server2
