apiVersion: v1
kind: Service
metadata:
  name: open5gs-mongodb
spec:
  ports:
  - port: 27017
  selector:
    app: open5gs-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-mongodb
spec:
  selector:
    matchLabels:
      app: open5gs-mongodb
  template:
    metadata:
      labels:
        app: open5gs-mongodb
    spec:
      containers:
      - image: free5gmano/nextepc-mongodb
        name: open5gs-mongodb
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: mongodb-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongodb-persistent-storage
        persistentVolumeClaim:
          claimName: open5gs-mongodb
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: open5gs-mongodb-pv-volume
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open5gs-mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

